### ISSUE TITLE
Тексты ревардов

### ISSUE THREAD

**Issue by Format-X22** [GolosChain/push-service#5]
Необходимо написать и сделать перевод для текстов пушей для событий получения авторской награды и кураторской награды (reward и curatorReward).

**Comment by jevgenika** [comment]
Текста для пушей прописаны в [доке](https://docs.google.com/spreadsheets/d/1KA8pwTx423bDXL-8z1YDLzT-4HdepIv9rBdBKWiaLs4/edit?usp=sharing)
